# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

splitsub_to_splitmask <- function(splits, p1, p2) {
    .Call(`_emotionalabyss_splitsub_to_splitmask`, splits, p1, p2)
}

splitmask_to_splitsub <- function(splitmask) {
    .Call(`_emotionalabyss_splitmask_to_splitsub`, splitmask)
}

row_intersection <- function(mat1, mat2) {
    .Call(`_emotionalabyss_row_intersection`, mat1, mat2)
}

row_difference <- function(mat1, mat2) {
    .Call(`_emotionalabyss_row_difference`, mat1, mat2)
}

splitsub_to_groupmask <- function(splits, p1, p2) {
    .Call(`_emotionalabyss_splitsub_to_groupmask`, splits, p1, p2)
}

mat_unique <- function(A) {
    .Call(`_emotionalabyss_mat_unique`, A)
}

mask_oneval <- function(A, mask, val) {
    .Call(`_emotionalabyss_mask_oneval`, A, mask, val)
}

mask_oneval_sum <- function(A, mask, val) {
    .Call(`_emotionalabyss_mask_oneval_sum`, A, mask, val)
}

mat_to_vec_by_region <- function(A, mask, unique_regions) {
    .Call(`_emotionalabyss_mat_to_vec_by_region`, A, mask, unique_regions)
}

cube_to_mat_by_region <- function(C, mask, unique_regions) {
    .Call(`_emotionalabyss_cube_to_mat_by_region`, C, mask, unique_regions)
}

unmask_vector <- function(beta, regions, mask) {
    .Call(`_emotionalabyss_unmask_vector`, beta, regions, mask)
}

splitmask_focus <- function(mask_of_splits, onesplit, radius_int = 1L) {
    .Call(`_emotionalabyss_splitmask_focus`, mask_of_splits, onesplit, radius_int)
}

number_availables <- function(splitmask_focus) {
    .Call(`_emotionalabyss_number_availables`, splitmask_focus)
}

setdiff <- function(x, y) {
    .Call(`_emotionalabyss_setdiff`, x, y)
}

X2Dgrid <- function(x1, x2) {
    .Call(`_emotionalabyss_X2Dgrid`, x1, x2)
}

X2Dgrid_alt <- function(x1, x2) {
    .Call(`_emotionalabyss_X2Dgrid_alt`, x1, x2)
}

exclude <- function(test, excl) {
    .Call(`_emotionalabyss_exclude`, test, excl)
}

nonzeromean <- function(mat_mcmc) {
    .Call(`_emotionalabyss_nonzeromean`, mat_mcmc)
}

col_eq_check <- function(A) {
    .Call(`_emotionalabyss_col_eq_check`, A)
}

col_sums <- function(matty) {
    .Call(`_emotionalabyss_col_sums`, matty)
}

hat_alt <- function(X) {
    .Call(`_emotionalabyss_hat_alt`, X)
}

hat <- function(X) {
    .Call(`_emotionalabyss_hat`, X)
}

cube_mean <- function(X, dim) {
    .Call(`_emotionalabyss_cube_mean`, X, dim)
}

cube_sum <- function(X, dim) {
    .Call(`_emotionalabyss_cube_sum`, X, dim)
}

cube_prod <- function(x, dim) {
    .Call(`_emotionalabyss_cube_prod`, x, dim)
}

index_to_subscript <- function(index, m) {
    .Call(`_emotionalabyss_index_to_subscript`, index, m)
}

gini <- function(x, p) {
    .Call(`_emotionalabyss_gini`, x, p)
}

find_avail <- function(tied, n) {
    .Call(`_emotionalabyss_find_avail`, tied, n)
}

find_first_unique <- function(x) {
    .Call(`_emotionalabyss_find_first_unique`, x)
}

find_ties <- function(x) {
    .Call(`_emotionalabyss_find_ties`, x)
}

pnorm01_vec <- function(x, lower = 1L, logged = 0L) {
    .Call(`_emotionalabyss_pnorm01_vec`, x, lower, logged)
}

qnorm01_vec <- function(x, lower = 1L, logged = 0L) {
    .Call(`_emotionalabyss_qnorm01_vec`, x, lower, logged)
}

log1p_vec <- function(x) {
    .Call(`_emotionalabyss_log1p_vec`, x)
}

usetdiff <- function(x, y) {
    .Call(`_emotionalabyss_usetdiff`, x, y)
}

single_split <- function(Jcoarse, where, p) {
    .Call(`_emotionalabyss_single_split`, Jcoarse, where, p)
}

single_split_new <- function(Jcoarse, where, p) {
    .Call(`_emotionalabyss_single_split_new`, Jcoarse, where, p)
}

multi_split <- function(Jcoarse, where, p) {
    .Call(`_emotionalabyss_multi_split`, Jcoarse, where, p)
}

multi_split_old <- function(Jcoarse, where, p) {
    .Call(`_emotionalabyss_multi_split_old`, Jcoarse, where, p)
}

multi_split_ones <- function(where, p) {
    .Call(`_emotionalabyss_multi_split_ones`, where, p)
}

multi_split_ones_v2 <- function(where, p) {
    .Call(`_emotionalabyss_multi_split_ones_v2`, where, p)
}

split_fix <- function(in_splits, stage) {
    .Call(`_emotionalabyss_split_fix`, in_splits, stage)
}

stage_fix <- function(in_splits) {
    .Call(`_emotionalabyss_stage_fix`, in_splits)
}

stretch_vec <- function(locations, base, dim) {
    .Call(`_emotionalabyss_stretch_vec`, locations, base, dim)
}

reshaper <- function(J_field, s) {
    .Call(`_emotionalabyss_reshaper`, J_field, s)
}

splits_truncate <- function(splits, k) {
    .Call(`_emotionalabyss_splits_truncate`, splits, k)
}

splits_augmentation <- function(splits) {
    .Call(`_emotionalabyss_splits_augmentation`, splits)
}

merge_splits <- function(old_splits, new_splits) {
    .Call(`_emotionalabyss_merge_splits`, old_splits, new_splits)
}

Ares <- function(L1, L2, L) {
    .Call(`_emotionalabyss_Ares`, L1, L2, L)
}

update_scale <- function(Di, D1, D2, A, X1, X2, theta1, theta2) {
    .Call(`_emotionalabyss_update_scale`, Di, D1, D2, A, X1, X2, theta1, theta2)
}

rndpp_mvnormal <- function(n, mean, sigma) {
    .Call(`_emotionalabyss_rndpp_mvnormal`, n, mean, sigma)
}

rndpp_mvnormal1 <- function(n, mean, sigma) {
    .Call(`_emotionalabyss_rndpp_mvnormal1`, n, mean, sigma)
}

rndpp_mvnormal2 <- function(n, mu, sigma) {
    .Call(`_emotionalabyss_rndpp_mvnormal2`, n, mu, sigma)
}

sample_index <- function(n, vsize) {
    .Call(`_emotionalabyss_sample_index`, n, vsize)
}

rndpp_unif_int <- function(maxi) {
    .Call(`_emotionalabyss_rndpp_unif_int`, maxi)
}

sample_one_int <- function(vsize) {
    .Call(`_emotionalabyss_sample_one_int`, vsize)
}

boolbern <- function(p) {
    .Call(`_emotionalabyss_boolbern`, p)
}

rndpp_discrete <- function(probs) {
    .Call(`_emotionalabyss_rndpp_discrete`, probs)
}

rndpp_sample1 <- function(fromvec, probs) {
    .Call(`_emotionalabyss_rndpp_sample1`, fromvec, probs)
}

pweight <- function(avail, p, current_split, lev, tot) {
    .Call(`_emotionalabyss_pweight`, avail, p, current_split, lev, tot)
}

rndpp_sample1_comp_alt <- function(x, p, current_split, decay = 4.0) {
    .Call(`_emotionalabyss_rndpp_sample1_comp_alt`, x, p, current_split, decay)
}

rndpp_sample1_comp <- function(x, p, current_split, lev, tot = 4.0) {
    .Call(`_emotionalabyss_rndpp_sample1_comp`, x, p, current_split, lev, tot)
}

rndpp_sample <- function(x, n) {
    .Call(`_emotionalabyss_rndpp_sample`, x, n)
}

rndpp_shuffle <- function(x) {
    .Call(`_emotionalabyss_rndpp_shuffle`, x)
}

rndpp_bern <- function(p) {
    .Call(`_emotionalabyss_rndpp_bern`, p)
}

rndpp_gamma <- function(alpha, beta) {
    .Call(`_emotionalabyss_rndpp_gamma`, alpha, beta)
}

rndpp_normal <- function(mean, sigma) {
    .Call(`_emotionalabyss_rndpp_normal`, mean, sigma)
}

rndpp_stdmvnormal <- function(n, dimension) {
    .Call(`_emotionalabyss_rndpp_stdmvnormal`, n, dimension)
}

rndpp_mvt <- function(n, mu, sigma, df) {
    .Call(`_emotionalabyss_rndpp_mvt`, n, mu, sigma, df)
}

#' Sample from Truncated Normal using Botev (2017)
#' 
#' @param mean A p-dimensional mean vector
#' @param l_in A p-dimensional vector of lower truncation limits (can be -Inf)
#' @param u_in A p-dimensional vector of upper truncation limits (can be Inf)
#' @param Sig A (p,p) covariance matrix.
#' @param n number of samples to extract
#' @export
mvtruncnormal <- function(mean, l_in, u_in, Sig, n) {
    .Call(`_emotionalabyss_mvtruncnormal`, mean, l_in, u_in, Sig, n)
}

#' Sample from Truncated and shifted Normal with Identity covariance
#' 
#' @param mean A p-dimensional mean vector
#' @param l_in A p-dimensional vector of lower truncation limits (can be -Inf)
#' @param u_in A p-dimensional vector of upper truncation limits (can be Inf)
#' @export
mvtruncnormal_eye1 <- function(mean, l_in, u_in) {
    .Call(`_emotionalabyss_mvtruncnormal_eye1`, mean, l_in, u_in)
}

