# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

setdiff <- function(x, y) {
    .Call(`_emotionalabyss_setdiff`, x, y)
}

X2Dgrid <- function(x1, x2) {
    .Call(`_emotionalabyss_X2Dgrid`, x1, x2)
}

X2Dgrid_alt <- function(x1, x2) {
    .Call(`_emotionalabyss_X2Dgrid_alt`, x1, x2)
}

exclude <- function(test, excl) {
    .Call(`_emotionalabyss_exclude`, test, excl)
}

nonzeromean <- function(mat_mcmc) {
    .Call(`_emotionalabyss_nonzeromean`, mat_mcmc)
}

col_eq_check <- function(A) {
    .Call(`_emotionalabyss_col_eq_check`, A)
}

col_sums <- function(matty) {
    .Call(`_emotionalabyss_col_sums`, matty)
}

hat_alt <- function(X) {
    .Call(`_emotionalabyss_hat_alt`, X)
}

hat <- function(X) {
    .Call(`_emotionalabyss_hat`, X)
}

cube_mean <- function(X, dim) {
    .Call(`_emotionalabyss_cube_mean`, X, dim)
}

cube_sum <- function(X, dim) {
    .Call(`_emotionalabyss_cube_sum`, X, dim)
}

cube_prod <- function(x, dim) {
    .Call(`_emotionalabyss_cube_prod`, x, dim)
}

index_to_subscript <- function(index, m) {
    .Call(`_emotionalabyss_index_to_subscript`, index, m)
}

gini <- function(x, p) {
    .Call(`_emotionalabyss_gini`, x, p)
}

find_avail <- function(tied, n) {
    .Call(`_emotionalabyss_find_avail`, tied, n)
}

find_first_unique <- function(x) {
    .Call(`_emotionalabyss_find_first_unique`, x)
}

find_ties <- function(x) {
    .Call(`_emotionalabyss_find_ties`, x)
}

rndppll_mvnormal <- function(n, mean, sigma) {
    .Call(`_emotionalabyss_rndppll_mvnormal`, n, mean, sigma)
}

rndpp_mvnormal <- function(n, mean, sigma) {
    .Call(`_emotionalabyss_rndpp_mvnormal`, n, mean, sigma)
}

rndpp_mvnormal2 <- function(n, mu, sigma) {
    .Call(`_emotionalabyss_rndpp_mvnormal2`, n, mu, sigma)
}

rndpp_mvnormalnew <- function(n, mean, sigma) {
    .Call(`_emotionalabyss_rndpp_mvnormalnew`, n, mean, sigma)
}

